// bosssim-data.js — GENERATED by tools/bosssim_data.mjs. Do not edit by hand.
//
// What the game's bosses and pets were measured doing, in the game itself:
// tools/bossmeasure.gd and tools/petmeasure.gd, run headless against the game
// project (BOSSSIM.md says how). Per boss, per stance (the player in its reach,
// or at range) and per phase: hits a second on a player who never moves, by
// what dealt them, and what the boss put on the floor a minute. Per pet: shots
// a second into a boss at five attack speeds, and anything else it dealt.
globalThis.BOSSSIM_DATA = {
 "game": "0.11.5",
 "measured": "2026-10-07",
 "seconds": {
  "boss": 300,
  "pet": 120
 },
 "bosses": {
  "light": {
   "element": "Light",
   "maxHp": 4576,
   "spike": 24,
   "swing": 28,
   "pillar": 16,
   "puddle": null,
   "melee": [
    {
     "swing": 0.663,
     "spike": 0.657,
     "pillar": 0,
     "puddle": 0,
     "floor": {
      "spikes": 345,
      "pillars": 0,
      "stalkers": 0,
      "puddles": 0
     }
    },
    {
     "swing": 0.663,
     "spike": 0.707,
     "pillar": 1.403,
     "puddle": 0,
     "floor": {
      "spikes": 610,
      "pillars": 84,
      "stalkers": 7,
      "puddles": 0
     }
    },
    {
     "swing": 0.663,
     "spike": 0.817,
     "pillar": 2.26,
     "puddle": 0,
     "floor": {
      "spikes": 745,
      "pillars": 136,
      "stalkers": 11,
      "puddles": 0
     }
    }
   ],
   "range": [
    {
     "swing": 0,
     "spike": 1.027,
     "pillar": 0,
     "puddle": 0,
     "floor": {
      "spikes": 343,
      "pillars": 929,
      "stalkers": 0,
      "puddles": 0
     }
    },
    {
     "swing": 0,
     "spike": 1.037,
     "pillar": 1.293,
     "puddle": 0,
     "floor": {
      "spikes": 599,
      "pillars": 907,
      "stalkers": 7,
      "puddles": 0
     }
    },
    {
     "swing": 0,
     "spike": 1.02,
     "pillar": 2.083,
     "puddle": 0,
     "floor": {
      "spikes": 749,
      "pillars": 980,
      "stalkers": 11,
      "puddles": 0
     }
    }
   ]
  },
  "wind": {
   "element": "Wind",
   "maxHp": 4992,
   "spike": 19,
   "swing": 28,
   "pillar": 13,
   "puddle": null,
   "melee": [
    {
     "swing": 0.663,
     "spike": 0.653,
     "pillar": 0,
     "puddle": 0,
     "floor": {
      "spikes": 348,
      "pillars": 0,
      "stalkers": 0,
      "puddles": 0
     }
    },
    {
     "swing": 0.663,
     "spike": 0.72,
     "pillar": 1.403,
     "puddle": 0,
     "floor": {
      "spikes": 592,
      "pillars": 84,
      "stalkers": 7,
      "puddles": 0
     }
    },
    {
     "swing": 0.663,
     "spike": 0.787,
     "pillar": 2.26,
     "puddle": 0,
     "floor": {
      "spikes": 722,
      "pillars": 136,
      "stalkers": 11,
      "puddles": 0
     }
    }
   ],
   "range": [
    {
     "swing": 0,
     "spike": 1.02,
     "pillar": 0,
     "puddle": 0,
     "floor": {
      "spikes": 357,
      "pillars": 929,
      "stalkers": 0,
      "puddles": 0
     }
    },
    {
     "swing": 0,
     "spike": 1.037,
     "pillar": 1.293,
     "puddle": 0,
     "floor": {
      "spikes": 587,
      "pillars": 901,
      "stalkers": 7,
      "puddles": 0
     }
    },
    {
     "swing": 0,
     "spike": 1.013,
     "pillar": 2.083,
     "puddle": 0,
     "floor": {
      "spikes": 721,
      "pillars": 993,
      "stalkers": 11,
      "puddles": 0
     }
    }
   ]
  },
  "water": {
   "element": "Water",
   "maxHp": 5616,
   "spike": 26,
   "swing": 40,
   "pillar": 16,
   "puddle": 2,
   "melee": [
    {
     "swing": 0.663,
     "spike": 0.65,
     "pillar": 0,
     "puddle": 0.95,
     "floor": {
      "spikes": 353,
      "pillars": 0,
      "stalkers": 0,
      "puddles": 187
     }
    },
    {
     "swing": 0.663,
     "spike": 0.707,
     "pillar": 1.4,
     "puddle": 1.533,
     "floor": {
      "spikes": 599,
      "pillars": 84,
      "stalkers": 7,
      "puddles": 323
     }
    },
    {
     "swing": 0.663,
     "spike": 0.83,
     "pillar": 2.253,
     "puddle": 1.787,
     "floor": {
      "spikes": 721,
      "pillars": 136,
      "stalkers": 11,
      "puddles": 379
     }
    }
   ],
   "range": [
    {
     "swing": 0,
     "spike": 1.023,
     "pillar": 0,
     "puddle": 2.623,
     "floor": {
      "spikes": 353,
      "pillars": 925,
      "stalkers": 0,
      "puddles": 677
     }
    },
    {
     "swing": 0,
     "spike": 1.033,
     "pillar": 1.29,
     "puddle": 2.433,
     "floor": {
      "spikes": 597,
      "pillars": 900,
      "stalkers": 7,
      "puddles": 731
     }
    },
    {
     "swing": 0,
     "spike": 1.013,
     "pillar": 2.077,
     "puddle": 2.88,
     "floor": {
      "spikes": 756,
      "pillars": 987,
      "stalkers": 11,
      "puddles": 862
     }
    }
   ]
  },
  "ice": {
   "element": "Ice",
   "maxHp": 6188,
   "spike": 27,
   "swing": 40,
   "pillar": 17,
   "puddle": 2,
   "melee": [
    {
     "swing": 0.663,
     "spike": 0.647,
     "pillar": 0,
     "puddle": 1.03,
     "floor": {
      "spikes": 357,
      "pillars": 0,
      "stalkers": 0,
      "puddles": 103
     }
    },
    {
     "swing": 0.663,
     "spike": 0.937,
     "pillar": 1.4,
     "puddle": 1.26,
     "floor": {
      "spikes": 620,
      "pillars": 84,
      "stalkers": 7,
      "puddles": 176
     }
    },
    {
     "swing": 0.663,
     "spike": 0.977,
     "pillar": 2.253,
     "puddle": 1.467,
     "floor": {
      "spikes": 709,
      "pillars": 136,
      "stalkers": 11,
      "puddles": 199
     }
    }
   ],
   "range": [
    {
     "swing": 0,
     "spike": 1.033,
     "pillar": 0,
     "puddle": 1.903,
     "floor": {
      "spikes": 339,
      "pillars": 929,
      "stalkers": 0,
      "puddles": 355
     }
    },
    {
     "swing": 0,
     "spike": 1.21,
     "pillar": 1.29,
     "puddle": 1.707,
     "floor": {
      "spikes": 599,
      "pillars": 910,
      "stalkers": 7,
      "puddles": 388
     }
    },
    {
     "swing": 0,
     "spike": 1.14,
     "pillar": 2.077,
     "puddle": 1.743,
     "floor": {
      "spikes": 710,
      "pillars": 972,
      "stalkers": 11,
      "puddles": 429
     }
    }
   ]
  },
  "earth": {
   "element": "Earth",
   "maxHp": 7384,
   "spike": 53,
   "swing": 56,
   "pillar": 34,
   "puddle": 4,
   "melee": [
    {
     "swing": 0.663,
     "spike": 0.657,
     "pillar": 0,
     "puddle": 0.72,
     "floor": {
      "spikes": 332,
      "pillars": 0,
      "stalkers": 0,
      "puddles": 119
     }
    },
    {
     "swing": 0.663,
     "spike": 1.117,
     "pillar": 1.4,
     "puddle": 0.63,
     "floor": {
      "spikes": 598,
      "pillars": 84,
      "stalkers": 7,
      "puddles": 207
     }
    },
    {
     "swing": 0.663,
     "spike": 1.28,
     "pillar": 2.253,
     "puddle": 0.99,
     "floor": {
      "spikes": 744,
      "pillars": 136,
      "stalkers": 11,
      "puddles": 263
     }
    }
   ],
   "range": [
    {
     "swing": 0,
     "spike": 1.03,
     "pillar": 0,
     "puddle": 1.07,
     "floor": {
      "spikes": 344,
      "pillars": 929,
      "stalkers": 0,
      "puddles": 442
     }
    },
    {
     "swing": 0,
     "spike": 1.4,
     "pillar": 1.29,
     "puddle": 1.177,
     "floor": {
      "spikes": 588,
      "pillars": 940,
      "stalkers": 7,
      "puddles": 498
     }
    },
    {
     "swing": 0,
     "spike": 1.413,
     "pillar": 2.077,
     "puddle": 0.94,
     "floor": {
      "spikes": 725,
      "pillars": 1002,
      "stalkers": 11,
      "puddles": 554
     }
    }
   ]
  },
  "fire": {
   "element": "Fire",
   "maxHp": 9200,
   "spike": 60,
   "swing": 79,
   "pillar": 39,
   "puddle": 5,
   "melee": [
    {
     "swing": 0.663,
     "spike": 0.653,
     "pillar": 0,
     "puddle": 1.773,
     "floor": {
      "spikes": 339,
      "pillars": 0,
      "stalkers": 0,
      "puddles": 148
     }
    },
    {
     "swing": 0.663,
     "spike": 0.707,
     "pillar": 1.4,
     "puddle": 1.733,
     "floor": {
      "spikes": 583,
      "pillars": 84,
      "stalkers": 7,
      "puddles": 263
     }
    },
    {
     "swing": 0.663,
     "spike": 0.843,
     "pillar": 2.253,
     "puddle": 1.703,
     "floor": {
      "spikes": 729,
      "pillars": 136,
      "stalkers": 11,
      "puddles": 335
     }
    }
   ],
   "range": [
    {
     "swing": 0,
     "spike": 1.023,
     "pillar": 0,
     "puddle": 2.913,
     "floor": {
      "spikes": 353,
      "pillars": 929,
      "stalkers": 0,
      "puddles": 586
     }
    },
    {
     "swing": 0,
     "spike": 1.033,
     "pillar": 1.29,
     "puddle": 2.62,
     "floor": {
      "spikes": 597,
      "pillars": 920,
      "stalkers": 7,
      "puddles": 649
     }
    },
    {
     "swing": 0,
     "spike": 1.007,
     "pillar": 2.077,
     "puddle": 2.577,
     "floor": {
      "spikes": 747,
      "pillars": 974,
      "stalkers": 11,
      "puddles": 737
     }
    }
   ]
  },
  "crowned": {
   "element": "Dark",
   "maxHp": 13800,
   "spike": 91,
   "swing": 110,
   "pillar": 59,
   "puddle": 4,
   "melee": [
    {
     "swing": 0.663,
     "spike": 0.647,
     "pillar": 0,
     "puddle": 0.707,
     "floor": {
      "spikes": 356,
      "pillars": 0,
      "stalkers": 0,
      "puddles": 121
     }
    },
    {
     "swing": 0.663,
     "spike": 0.71,
     "pillar": 1.4,
     "puddle": 0.947,
     "floor": {
      "spikes": 620,
      "pillars": 84,
      "stalkers": 7,
      "puddles": 226
     }
    },
    {
     "swing": 0.663,
     "spike": 0.81,
     "pillar": 2.253,
     "puddle": 1.043,
     "floor": {
      "spikes": 735,
      "pillars": 136,
      "stalkers": 11,
      "puddles": 260
     }
    }
   ],
   "range": [
    {
     "swing": 0,
     "spike": 1.027,
     "pillar": 0,
     "puddle": 1.297,
     "floor": {
      "spikes": 350,
      "pillars": 925,
      "stalkers": 0,
      "puddles": 438
     }
    },
    {
     "swing": 0,
     "spike": 1.01,
     "pillar": 1.29,
     "puddle": 1.533,
     "floor": {
      "spikes": 623,
      "pillars": 941,
      "stalkers": 7,
      "puddles": 525
     }
    },
    {
     "swing": 0,
     "spike": 1.027,
     "pillar": 2.077,
     "puddle": 1.097,
     "floor": {
      "spikes": 704,
      "pillars": 990,
      "stalkers": 11,
      "puddles": 538
     }
    }
   ]
  }
 },
 "pets": {
  "petboss": {
   "damage": 54,
   "cooldown": 2,
   "melee": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.5,
     0.558,
     0.625,
     0.683,
     0.75
    ],
    "extra": [
     7.125,
     8.333,
     10.083,
     9.583,
     11.667
    ]
   },
   "range": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.5,
     0.558,
     0.625,
     0.683,
     0.75
    ],
    "extra": [
     5.75,
     9.25,
     9.25,
     11.125,
     9.875
    ]
   }
  },
  "petfiresprite": {
   "damage": 44,
   "cooldown": 2,
   "melee": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.5,
     0.558,
     0.625,
     0.683,
     0.75
    ],
    "extra": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   "range": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.492,
     0.558,
     0.617,
     0.683,
     0.75
    ],
    "extra": [
     0,
     0,
     0,
     0,
     0
    ]
   }
  },
  "petmage": {
   "damage": 36,
   "cooldown": 2,
   "melee": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.5,
     0.558,
     0.617,
     0.683,
     0.75
    ],
    "extra": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   "range": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.5,
     0.558,
     0.617,
     0.683,
     0.75
    ],
    "extra": [
     0,
     0,
     0,
     0,
     0
    ]
   }
  },
  "petpoisonslimelarge": {
   "damage": 52,
   "cooldown": 2,
   "melee": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.5,
     0.558,
     0.625,
     0.683,
     0.75
    ],
    "extra": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   "range": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.5,
     0.558,
     0.625,
     0.683,
     0.75
    ],
    "extra": [
     0,
     0,
     0,
     0,
     0
    ]
   }
  },
  "petpoisonslimesmall": {
   "damage": 46,
   "cooldown": 2,
   "melee": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.417,
     0.467,
     0.508,
     0.567,
     0.608
    ],
    "extra": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   "range": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.417,
     0.467,
     0.508,
     0.567,
     0.608
    ],
    "extra": [
     0,
     0,
     0,
     0,
     0
    ]
   }
  },
  "petsniper": {
   "damage": 38,
   "cooldown": 2,
   "melee": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.5,
     0.558,
     0.625,
     0.683,
     0.75
    ],
    "extra": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   "range": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.492,
     0.558,
     0.625,
     0.683,
     0.75
    ],
    "extra": [
     0,
     0,
     0,
     0,
     0
    ]
   }
  },
  "petelectricsprite": {
   "damage": 40,
   "cooldown": 2,
   "melee": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.5,
     0.558,
     0.625,
     0.683,
     0.75
    ],
    "extra": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   "range": {
    "haste": [
     1,
     1.25,
     1.5,
     1.75,
     2
    ],
    "shots": [
     0.492,
     0.558,
     0.617,
     0.683,
     0.75
    ],
    "extra": [
     0,
     0,
     0,
     0,
     0
    ]
   }
  }
 }
};
